package com.example.imagemvvmtask.viewmodel

import androidx.lifecycle.ViewModel
import com.example.imagemvvmtask.R
import com.example.imagemvvmtask.models.Photos
import com.example.imagemvvmtask.views.MyAdapter

/**
 * 1. This is ViewModel Class.
 * 2. Here we Store the Photos in an Array.
 * 3. We are returning the ArrayList as MyAdapter Return Type.
 */

class PhotosViewModel : ViewModel() {
    fun addPhotos(): MyAdapter {
        val newArrayList = arrayListOf<Photos>()
        val imageId: Array<Int> = arrayOf(
            R.drawable.sky,
            R.drawable.android,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.spiderman,
            R.drawable.laptop,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.laptop,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.laptop,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.spiderman,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.laptop,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.laptop,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.laptop,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.laptop,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.laptop,
            R.drawable.android,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.sky,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.laptop,
            R.drawable.person,
            R.drawable.sky,
            R.drawable.insta,
            R.drawable.spiderman,
            R.drawable.android,
            R.drawable.laptop

        )
        for (i in imageId.indices) {
            val pics = Photos(imageId[i])
            newArrayList.add(pics)
        }
        return MyAdapter(newArrayList)
    }
}